FROM ubuntu:jammy AS jammy

RUN apt update;
RUN apt install -y wget curl tree git gcc build-essential kbuild libelf-dev;
RUN apt-get -y install linux-headers*generic
RUN apt-get -y install linux-aws-headers* || true
RUN apt clean all

ADD . /elkeid_driver
WORKDIR /elkeid_driver
RUN bash ./batch_compile.sh