FROM ubuntu:xenial AS xenial

RUN apt update;
RUN apt install -y wget curl tree git gcc build-essential kbuild libelf-dev;
RUN apt-get -y install linux-azure-headers* || true
RUN apt clean all

ADD . /elkeid_driver
WORKDIR /elkeid_driver
RUN bash ./batch_compile.sh

RUN apt-get -y remove linux-azure-headers* || true
